export const HEROES = {
    abaddon: { id: 102, name: 'Abaddon' },
    alchemist: { id: 73, name: 'Alchemist' },
    axe: { id: 2, name: 'Axe' },
    bane: { id: 3, name: 'Bane' },
    batrider: { id: 65, name: 'Batrider' },
    beastmaster: { id: 38, name: 'Beastmaster' },
    bloodseeker: { id: 4, name: 'Bloodseeker' },
    bounty: { id: 62, name: 'Bounty Hunter' },
    brew: { id: 78, name: 'Brewmaster' },
    bristle: { id: 99, name: 'Bristleback' },
    brood: { id: 61, name: 'Broodmother' },
    centaur: { id: 96, name: 'Centaur Warrunner' },
    chaos: { id: 81, name: 'Chaos Knight' },
    chen: { id: 66, name: 'Chen' },
    clinkz: { id: 56, name: 'Clinkz' },
    clock: { id: 51, name: 'Clockwerk' },
    crystal: { id: 5, name: 'Crystal Maiden' },
    dark_seer: { id: 55, name: 'Dark Seer' },
    dawnbreaker: { id: 135, name: 'Dawnbreaker' },
    dazzle: { id: 50, name: 'Dazzle' },
    death_prophet: { id: 43, name: 'Death Prophet' },
    disruptor: { id: 87, name: 'Disruptor' },
    doom: { id: 69, name: 'Doom' },
    dragon_knight: { id: 49, name: 'Dragon Knight' },
    drow: { id: 6, name: 'Drow Ranger' },
    earth_spirit: { id: 107, name: 'Earth Spirit' },
    earthshaker: { id: 7, name: 'Earthshaker' },
    elder_titan: { id: 103, name: 'Elder Titan' },
    ember: { id: 106, name: 'Ember Spirit' },
    enchantress: { id: 58, name: 'Enchantress' },
    enigma: { id: 33, name: 'Enigma' },
    faceless_void: { id: 41, name: 'Faceless Void' },
    grimstroke: { id: 121, name: 'Grimstroke' },
    gyrocopter: { id: 72, name: 'Gyrocopter' },
    hoodwink: { id: 123, name: 'Hoodwink' },
    huskar: { id: 59, name: 'Huskar' },
    invoker: { id: 74, name: 'Invoker' },
    io: { id: 91, name: 'Io' },
    jakiro: { id: 64, name: 'Jakiro' },
    juggernaut: { id: 8, name: 'Juggernaut' },
    keeper: { id: 90, name: 'Keeper of the Light' },
    kunkka: { id: 23, name: 'Kunkka' },
    legion: { id: 104, name: 'Legion Commander' },
    leshrac: { id: 52, name: 'Leshrac' },
    lich: { id: 31, name: 'Lich' },
    lifestealer: { id: 54, name: 'Lifestealer' },
    lina: { id: 25, name: 'Lina' },
    lion: { id: 26, name: 'Lion' },
    lone_druid: { id: 80, name: 'Lone Druid' },
    luna: { id: 48, name: 'Luna' },
    lycan: { id: 77, name: 'Lycan' },
    magnus: { id: 97, name: 'Magnus' },
    mars: { id: 129, name: 'Mars' },
    medusa: { id: 94, name: 'Medusa' },
    meepo: { id: 82, name: 'Meepo' },
    mirana: { id: 9, name: 'Mirana' },
    monkey_king: { id: 114, name: 'Monkey King' },
    morphling: { id: 10, name: 'Morphling' },
    naga: { id: 89, name: 'Naga Siren' },
    natures_prophet: { id: 53, name: "Nature's Prophet" },
    necrophos: { id: 36, name: 'Necrophos' },
    night_stalker: { id: 60, name: 'Night Stalker' },
    nyx: { id: 88, name: 'Nyx Assassin' },
    ogre: { id: 84, name: 'Ogre Magi' },
    omniknight: { id: 57, name: 'Omniknight' },
    oracle: { id: 111, name: 'Oracle' },
    pangolier: { id: 120, name: 'Pangolier' },
    phantom_assassin: { id: 44, name: 'Phantom Assassin' },
    phantom_lancer: { id: 12, name: 'Phantom Lancer' },
    phoenix: { id: 110, name: 'Phoenix' },
    primal_beast: { id: 137, name: 'Primal Beast' },
    puck: { id: 13, name: 'Puck' },
    pudge: { id: 14, name: 'Pudge' },
    pugna: { id: 45, name: 'Pugna' },
    queen_of_pain: { id: 39, name: 'Queen of Pain' },
    razor: { id: 15, name: 'Razor' },
    riki: { id: 32, name: 'Riki' },
    rubick: { id: 86, name: 'Rubick' },
    sand_king: { id: 16, name: 'Sand King' },
    shadow_demon: { id: 79, name: 'Shadow Demon' },
    shadow_fiend: { id: 11, name: 'Shadow Fiend' },
    shadow_shaman: { id: 27, name: 'Shadow Shaman' },
    silencer: { id: 75, name: 'Silencer' },
    skywrath: { id: 101, name: 'Skywrath Mage' },
    slardar: { id: 28, name: 'Slardar' },
    slark: { id: 93, name: 'Slark' },
    snapfire: { id: 128, name: 'Snapfire' },
    sniper: { id: 35, name: 'Sniper' },
    spectre: { id: 67, name: 'Spectre' },
    spirit_breaker: { id: 71, name: 'Spirit Breaker' },
    storm: { id: 17, name: 'Storm Spirit' },
    sven: { id: 18, name: 'Sven' },
    techies: { id: 105, name: 'Techies' },
    templar_assassin: { id: 46, name: 'Templar Assassin' },
    terrorblade: { id: 109, name: 'Terrorblade' },
    tidehunter: { id: 29, name: 'Tidehunter' },
    timber: { id: 98, name: 'Timbersaw' },
    tinker: { id: 34, name: 'Tinker' },
    tiny: { id: 19, name: 'Tiny' },
    treant: { id: 83, name: 'Treant Protector' },
    troll: { id: 95, name: 'Troll Warlord' },
    tusk: { id: 100, name: 'Tusk' },
    underlord: { id: 108, name: 'Underlord' },
    undying: { id: 85, name: 'Undying' },
    ursa: { id: 70, name: 'Ursa' },
    vengeful: { id: 20, name: 'Vengeful Spirit' },
    venomancer: { id: 40, name: 'Venomancer' },
    viper: { id: 47, name: 'Viper' },
    visage: { id: 92, name: 'Visage' },
    void_spirit: { id: 126, name: 'Void Spirit' },
    warlock: { id: 37, name: 'Warlock' },
    weaver: { id: 63, name: 'Weaver' },
    windranger: { id: 21, name: 'Windranger' },
    winter_wyvern: { id: 112, name: 'Winter Wyvern' },
    witch_doctor: { id: 30, name: 'Witch Doctor' },
    wraith_king: { id: 42, name: 'Wraith King' },
    zeus: { id: 22, name: 'Zeus' }
};